# Generated by Django 5.0.1 on 2026-03-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='population',
            field=models.PositiveIntegerField(blank=True, help_text='Catchment population of the facility', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='sam_prevalence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='SAM prevalence rate (%) of the region', max_digits=5, null=True),
        ),
    ]
