# Generated by Django 5.1.5 on 2026-08-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0003_add_opc_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="dhis2_org_unit_id",
            field=models.CharField(
                blank=True,
                help_text="DHIS2 organization unit UID for this facility",
                max_length=60,
                null=True,
            ),
        ),
    ]
