# Generated by Django 5.1.5 on 2026-08-28 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0004_facility_dhis2_org_unit_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dhis2Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "server_url",
                    models.URLField(
                        help_text="Base URL of the DHIS2 instance, e.g. https://dhis2.example.org"
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                (
                    "password",
                    models.CharField(
                        help_text="Stored in plain text — protect your DB",
                        max_length=255,
                    ),
                ),
                (
                    "api_token",
                    models.CharField(
                        blank=True,
                        help_text="Optional API token (overrides username/password)",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "dataset_id",
                    models.CharField(
                        help_text="DHIS2 data set UID for CMAM/Nutrition report",
                        max_length=60,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "DHIS2 Configuration",
                "verbose_name_plural": "DHIS2 Configuration",
                "db_table": "dhis2_config",
            },
        ),
        migrations.CreateModel(
            name="Dhis2DataElementMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric_key",
                    models.CharField(
                        choices=[
                            ("sam_new_admissions", "SAM – New admissions (6-59m)"),
                            ("sam_readmissions", "SAM – Readmissions"),
                            ("sam_transfers_in", "SAM – Transfers in"),
                            ("sam_cured", "SAM – Cured discharges"),
                            ("sam_defaulted", "SAM – Defaulted"),
                            ("sam_deaths", "SAM – Deaths"),
                            ("sam_non_response", "SAM – Non-response"),
                            ("sam_transfers_out", "SAM – Transfers out (to IPC)"),
                            ("sam_total_active", "SAM – Total active at end of month"),
                            ("mam_new_admissions", "MAM – New admissions (6-59m)"),
                            ("mam_readmissions", "MAM – Readmissions"),
                            ("mam_cured", "MAM – Cured discharges"),
                            ("mam_defaulted", "MAM – Defaulted"),
                            ("mam_deaths", "MAM – Deaths"),
                            ("mam_non_response", "MAM – Non-response"),
                            ("mam_total_active", "MAM – Total active at end of month"),
                            ("ipc_admissions", "IPC – Admissions"),
                            ("ipc_discharges", "IPC – Discharges (cured)"),
                            ("ipc_deaths", "IPC – Deaths"),
                            ("total_visits", "Total OTP visits in period"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "data_element_uid",
                    models.CharField(help_text="DHIS2 data element UID", max_length=60),
                ),
                (
                    "category_option_combo_uid",
                    models.CharField(
                        blank=True,
                        help_text="DHIS2 category option combo UID (for disaggregated data elements)",
                        max_length=60,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "DHIS2 Data Element Mapping",
                "verbose_name_plural": "DHIS2 Data Element Mappings",
                "db_table": "dhis2_data_element_mapping",
            },
        ),
        migrations.CreateModel(
            name="Dhis2PushLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.CharField(
                        help_text="Reporting period, e.g. 202608", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="The JSON payload sent to DHIS2"),
                ),
                (
                    "response",
                    models.JSONField(
                        blank=True, help_text="DHIS2 API response", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dhis2_push_logs",
                        to="facilities.facility",
                    ),
                ),
                (
                    "pushed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dhis2_pushes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dhis2_push_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
