# Generated by Django 5.1.5 on 2026-08-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dhis2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dhis2dataelementmapping",
            name="metric_key",
            field=models.CharField(
                choices=[
                    (
                        "sam_opc_under6_new_male",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – New Enrollment Male",
                    ),
                    (
                        "sam_opc_under6_new_female",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – New Enrollment Female",
                    ),
                    (
                        "sam_opc_under6_old",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – Old Enrollments (Returned Defaulter + Referred In)",
                    ),
                    (
                        "sam_opc_under6_other",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – Other Enrollments (>=5 years)",
                    ),
                    (
                        "sam_opc_under6_male_cured",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – Male Cured",
                    ),
                    (
                        "sam_opc_under6_male_died",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – Male Died",
                    ),
                    (
                        "sam_opc_under6_male_defaulted",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – Male Defaulted",
                    ),
                    (
                        "sam_opc_under6_male_nr",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – Male Non-recovered",
                    ),
                    (
                        "sam_opc_under6_female_cured",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – Female Cured",
                    ),
                    (
                        "sam_opc_under6_female_died",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – Female Died",
                    ),
                    (
                        "sam_opc_under6_female_defaulted",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – Female Defaulted",
                    ),
                    (
                        "sam_opc_under6_female_nr",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – Female Non-recovered",
                    ),
                    (
                        "sam_opc_under6_referred_out",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – Referred out",
                    ),
                    (
                        "sam_opc_under6_exit_5plus",
                        "SAM OPC – <6 months at risk (WFL <-2SD/WFA<-2SD) – Exits >=5 years",
                    ),
                    (
                        "sam_opc_6_59_muac_new_male",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – New Enrollment Male",
                    ),
                    (
                        "sam_opc_6_59_muac_new_female",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – New Enrollment Female",
                    ),
                    (
                        "sam_opc_6_59_muac_old",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – Old Enrollments (Returned Defaulter + Referred In)",
                    ),
                    (
                        "sam_opc_6_59_muac_other",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – Other Enrollments (>=5 years)",
                    ),
                    (
                        "sam_opc_6_59_muac_male_cured",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – Male Cured",
                    ),
                    (
                        "sam_opc_6_59_muac_male_died",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – Male Died",
                    ),
                    (
                        "sam_opc_6_59_muac_male_defaulted",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – Male Defaulted",
                    ),
                    (
                        "sam_opc_6_59_muac_male_nr",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – Male Non-recovered",
                    ),
                    (
                        "sam_opc_6_59_muac_female_cured",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – Female Cured",
                    ),
                    (
                        "sam_opc_6_59_muac_female_died",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – Female Died",
                    ),
                    (
                        "sam_opc_6_59_muac_female_defaulted",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – Female Defaulted",
                    ),
                    (
                        "sam_opc_6_59_muac_female_nr",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – Female Non-recovered",
                    ),
                    (
                        "sam_opc_6_59_muac_referred_out",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – Referred out",
                    ),
                    (
                        "sam_opc_6_59_muac_exit_5plus",
                        "SAM OPC – 6-59 months (MUAC <11.5cm or WFL/WFH <-3SD) – Exits >=5 years",
                    ),
                    (
                        "sam_opc_6_59_oedema_new_male",
                        "SAM OPC – 6-59 months (oedema) – New Enrollment Male",
                    ),
                    (
                        "sam_opc_6_59_oedema_new_female",
                        "SAM OPC – 6-59 months (oedema) – New Enrollment Female",
                    ),
                    (
                        "sam_opc_6_59_oedema_old",
                        "SAM OPC – 6-59 months (oedema) – Old Enrollments (Returned Defaulter + Referred In)",
                    ),
                    (
                        "sam_opc_6_59_oedema_other",
                        "SAM OPC – 6-59 months (oedema) – Other Enrollments (>=5 years)",
                    ),
                    (
                        "sam_opc_6_59_oedema_male_cured",
                        "SAM OPC – 6-59 months (oedema) – Male Cured",
                    ),
                    (
                        "sam_opc_6_59_oedema_male_died",
                        "SAM OPC – 6-59 months (oedema) – Male Died",
                    ),
                    (
                        "sam_opc_6_59_oedema_male_defaulted",
                        "SAM OPC – 6-59 months (oedema) – Male Defaulted",
                    ),
                    (
                        "sam_opc_6_59_oedema_male_nr",
                        "SAM OPC – 6-59 months (oedema) – Male Non-recovered",
                    ),
                    (
                        "sam_opc_6_59_oedema_female_cured",
                        "SAM OPC – 6-59 months (oedema) – Female Cured",
                    ),
                    (
                        "sam_opc_6_59_oedema_female_died",
                        "SAM OPC – 6-59 months (oedema) – Female Died",
                    ),
                    (
                        "sam_opc_6_59_oedema_female_defaulted",
                        "SAM OPC – 6-59 months (oedema) – Female Defaulted",
                    ),
                    (
                        "sam_opc_6_59_oedema_female_nr",
                        "SAM OPC – 6-59 months (oedema) – Female Non-recovered",
                    ),
                    (
                        "sam_opc_6_59_oedema_referred_out",
                        "SAM OPC – 6-59 months (oedema) – Referred out",
                    ),
                    (
                        "sam_opc_6_59_oedema_exit_5plus",
                        "SAM OPC – 6-59 months (oedema) – Exits >=5 years",
                    ),
                    (
                        "sam_ipc_under6_severe_new_male",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – New Enrollment Male",
                    ),
                    (
                        "sam_ipc_under6_severe_new_female",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – New Enrollment Female",
                    ),
                    (
                        "sam_ipc_under6_severe_old",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – Old Enrollments (Returned Defaulter + Referred In)",
                    ),
                    (
                        "sam_ipc_under6_severe_other",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – Other Enrollments (>=5 years)",
                    ),
                    (
                        "sam_ipc_under6_severe_male_cured",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – Male Cured",
                    ),
                    (
                        "sam_ipc_under6_severe_male_died",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – Male Died",
                    ),
                    (
                        "sam_ipc_under6_severe_male_defaulted",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – Male Defaulted",
                    ),
                    (
                        "sam_ipc_under6_severe_male_nr",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – Male Non-recovered",
                    ),
                    (
                        "sam_ipc_under6_severe_female_cured",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – Female Cured",
                    ),
                    (
                        "sam_ipc_under6_severe_female_died",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – Female Died",
                    ),
                    (
                        "sam_ipc_under6_severe_female_defaulted",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – Female Defaulted",
                    ),
                    (
                        "sam_ipc_under6_severe_female_nr",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – Female Non-recovered",
                    ),
                    (
                        "sam_ipc_under6_severe_referred_out",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – Referred out",
                    ),
                    (
                        "sam_ipc_under6_severe_exit_5plus",
                        "SAM IPC – SAM <6mo (WFL <-3SD or MUAC <11.0cm or oedema) – Exits >=5 years",
                    ),
                    (
                        "sam_ipc_under6_moderate_new_male",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – New Enrollment Male",
                    ),
                    (
                        "sam_ipc_under6_moderate_new_female",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – New Enrollment Female",
                    ),
                    (
                        "sam_ipc_under6_moderate_old",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – Old Enrollments (Returned Defaulter + Referred In)",
                    ),
                    (
                        "sam_ipc_under6_moderate_other",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – Other Enrollments (>=5 years)",
                    ),
                    (
                        "sam_ipc_under6_moderate_male_cured",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – Male Cured",
                    ),
                    (
                        "sam_ipc_under6_moderate_male_died",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – Male Died",
                    ),
                    (
                        "sam_ipc_under6_moderate_male_defaulted",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – Male Defaulted",
                    ),
                    (
                        "sam_ipc_under6_moderate_male_nr",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – Male Non-recovered",
                    ),
                    (
                        "sam_ipc_under6_moderate_female_cured",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – Female Cured",
                    ),
                    (
                        "sam_ipc_under6_moderate_female_died",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – Female Died",
                    ),
                    (
                        "sam_ipc_under6_moderate_female_defaulted",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – Female Defaulted",
                    ),
                    (
                        "sam_ipc_under6_moderate_female_nr",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – Female Non-recovered",
                    ),
                    (
                        "sam_ipc_under6_moderate_referred_out",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – Referred out",
                    ),
                    (
                        "sam_ipc_under6_moderate_exit_5plus",
                        "SAM IPC – SAM <6mo (WFL <-2SD or WAZ <-2SD or MUAC 11.0-11.5cm) – Exits >=5 years",
                    ),
                    (
                        "sam_ipc_6_59_muac_new_male",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – New Enrollment Male",
                    ),
                    (
                        "sam_ipc_6_59_muac_new_female",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – New Enrollment Female",
                    ),
                    (
                        "sam_ipc_6_59_muac_old",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – Old Enrollments (Returned Defaulter + Referred In)",
                    ),
                    (
                        "sam_ipc_6_59_muac_other",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – Other Enrollments (>=5 years)",
                    ),
                    (
                        "sam_ipc_6_59_muac_male_cured",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – Male Cured",
                    ),
                    (
                        "sam_ipc_6_59_muac_male_died",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – Male Died",
                    ),
                    (
                        "sam_ipc_6_59_muac_male_defaulted",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – Male Defaulted",
                    ),
                    (
                        "sam_ipc_6_59_muac_male_nr",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – Male Non-recovered",
                    ),
                    (
                        "sam_ipc_6_59_muac_female_cured",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – Female Cured",
                    ),
                    (
                        "sam_ipc_6_59_muac_female_died",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – Female Died",
                    ),
                    (
                        "sam_ipc_6_59_muac_female_defaulted",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – Female Defaulted",
                    ),
                    (
                        "sam_ipc_6_59_muac_female_nr",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – Female Non-recovered",
                    ),
                    (
                        "sam_ipc_6_59_muac_referred_out",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – Referred out",
                    ),
                    (
                        "sam_ipc_6_59_muac_exit_5plus",
                        "SAM IPC – SAM 6-59mo (MUAC <11.5cm or WFL/WFH <-3SD) – Exits >=5 years",
                    ),
                    (
                        "sam_ipc_6_59_oedema_new_male",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – New Enrollment Male",
                    ),
                    (
                        "sam_ipc_6_59_oedema_new_female",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – New Enrollment Female",
                    ),
                    (
                        "sam_ipc_6_59_oedema_old",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – Old Enrollments (Returned Defaulter + Referred In)",
                    ),
                    (
                        "sam_ipc_6_59_oedema_other",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – Other Enrollments (>=5 years)",
                    ),
                    (
                        "sam_ipc_6_59_oedema_male_cured",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – Male Cured",
                    ),
                    (
                        "sam_ipc_6_59_oedema_male_died",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – Male Died",
                    ),
                    (
                        "sam_ipc_6_59_oedema_male_defaulted",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – Male Defaulted",
                    ),
                    (
                        "sam_ipc_6_59_oedema_male_nr",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – Male Non-recovered",
                    ),
                    (
                        "sam_ipc_6_59_oedema_female_cured",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – Female Cured",
                    ),
                    (
                        "sam_ipc_6_59_oedema_female_died",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – Female Died",
                    ),
                    (
                        "sam_ipc_6_59_oedema_female_defaulted",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – Female Defaulted",
                    ),
                    (
                        "sam_ipc_6_59_oedema_female_nr",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – Female Non-recovered",
                    ),
                    (
                        "sam_ipc_6_59_oedema_referred_out",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – Referred out",
                    ),
                    (
                        "sam_ipc_6_59_oedema_exit_5plus",
                        "SAM IPC – SAM 6-59mo (oedema/Marasmic kwashiorkor) – Exits >=5 years",
                    ),
                    (
                        "mam_opc_high_risk_new_male",
                        "MAM OPC – High Risk MAM 6-59 months – New Admissions Male",
                    ),
                    (
                        "mam_opc_high_risk_new_female",
                        "MAM OPC – High Risk MAM 6-59 months – New Admissions Female",
                    ),
                    (
                        "mam_opc_high_risk_old",
                        "MAM OPC – High Risk MAM 6-59 months – Old Enrollments (Returned Defaulter + Referred In)",
                    ),
                    (
                        "mam_opc_high_risk_male_cured",
                        "MAM OPC – High Risk MAM 6-59 months – Male Cured",
                    ),
                    (
                        "mam_opc_high_risk_male_died",
                        "MAM OPC – High Risk MAM 6-59 months – Male Died",
                    ),
                    (
                        "mam_opc_high_risk_male_defaulted",
                        "MAM OPC – High Risk MAM 6-59 months – Male Defaulted",
                    ),
                    (
                        "mam_opc_high_risk_male_nr",
                        "MAM OPC – High Risk MAM 6-59 months – Male Non-recovered",
                    ),
                    (
                        "mam_opc_high_risk_female_cured",
                        "MAM OPC – High Risk MAM 6-59 months – Female Cured",
                    ),
                    (
                        "mam_opc_high_risk_female_died",
                        "MAM OPC – High Risk MAM 6-59 months – Female Died",
                    ),
                    (
                        "mam_opc_high_risk_female_defaulted",
                        "MAM OPC – High Risk MAM 6-59 months – Female Defaulted",
                    ),
                    (
                        "mam_opc_high_risk_female_nr",
                        "MAM OPC – High Risk MAM 6-59 months – Female Non-recovered",
                    ),
                    (
                        "mam_opc_high_risk_referred_out",
                        "MAM OPC – High Risk MAM 6-59 months – Referred out",
                    ),
                    (
                        "mam_opc_other_new_male",
                        "MAM OPC – Other MAM cases 6-59 months – New Admissions Male",
                    ),
                    (
                        "mam_opc_other_new_female",
                        "MAM OPC – Other MAM cases 6-59 months – New Admissions Female",
                    ),
                    (
                        "mam_opc_other_old",
                        "MAM OPC – Other MAM cases 6-59 months – Old Enrollments (Returned Defaulter + Referred In)",
                    ),
                    (
                        "mam_opc_other_male_cured",
                        "MAM OPC – Other MAM cases 6-59 months – Male Cured",
                    ),
                    (
                        "mam_opc_other_male_died",
                        "MAM OPC – Other MAM cases 6-59 months – Male Died",
                    ),
                    (
                        "mam_opc_other_male_defaulted",
                        "MAM OPC – Other MAM cases 6-59 months – Male Defaulted",
                    ),
                    (
                        "mam_opc_other_male_nr",
                        "MAM OPC – Other MAM cases 6-59 months – Male Non-recovered",
                    ),
                    (
                        "mam_opc_other_female_cured",
                        "MAM OPC – Other MAM cases 6-59 months – Female Cured",
                    ),
                    (
                        "mam_opc_other_female_died",
                        "MAM OPC – Other MAM cases 6-59 months – Female Died",
                    ),
                    (
                        "mam_opc_other_female_defaulted",
                        "MAM OPC – Other MAM cases 6-59 months – Female Defaulted",
                    ),
                    (
                        "mam_opc_other_female_nr",
                        "MAM OPC – Other MAM cases 6-59 months – Female Non-recovered",
                    ),
                    (
                        "mam_opc_other_referred_out",
                        "MAM OPC – Other MAM cases 6-59 months – Referred out",
                    ),
                ],
                max_length=60,
                unique=True,
            ),
        ),
    ]
