# Generated by Django 5.0.1 on 2026-02-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcvisit',
            name='food_product_quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opcvisit',
            name='food_product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opcvisit',
            name='staff_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
