# Generated by Django 5.0.1 on 2026-02-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_opcvisit_food_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcregistration',
            name='mam_type',
            field=models.CharField(blank=True, choices=[('High-risk MAM', 'High-risk MAM'), ('Other MAM', 'Other MAM')], max_length=20, null=True),
        ),
    ]
