# Generated by Django 5.0.1 on 2026-02-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_add_mam_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcregistration',
            name='admission_criteria',
            field=models.CharField(blank=True, choices=[('MUAC <11.5cm', 'MUAC <11.5cm'), ('WFH/WFL <-3SD', 'WFH/WFL <-3SD'), ('Bilateral Oedema', 'Bilateral Oedema'), ('MUAC 11.5-12.4cm', 'MUAC 11.5-12.4cm'), ('WFH/WFL <-2SD', 'WFH/WFL <-2SD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opcregistration',
            name='admission_type',
            field=models.CharField(choices=[('New Admission', 'New Admission'), ('Readmission', 'Readmission'), ('Transfer In', 'Transfer In')], default='New Admission', max_length=20),
        ),
    ]
