# Generated by Django 5.0.1 on 2026-03-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_add_admission_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcregistration',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Auto-generated: CODE/NNN/SAM-OPC', max_length=30, null=True, unique=True),
        ),
    ]
