# Generated by Django 4.2.27 on 2026-06-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_add_registration_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcregistration",
            name="additional_medical_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="additional_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="amoxicillin_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="amoxicillin_dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="antimalarial_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="antimalarial_dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="breastfeeding_prospect",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="breastfeeding_status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="chest_indrawing",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="conjunctiva",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="cough",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="deworming_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="deworming_dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="diarrhoea",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="disability",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="disability_details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="ears_condition",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="eyes_condition",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="father_alive",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="folic_acid_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="folic_acid_dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="g6pd_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="hands_feet",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="house_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="immunization_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="lymph_nodes",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="malaria_test_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="malaria_test_result",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="measles_vaccine_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="measles_vaccine_dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="mother_alive",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="mouth_condition",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="next_visit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="oedema_duration_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="other_drug_1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="other_drug_1_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="other_drug_1_dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="other_drug_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="other_drug_2_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="other_drug_2_dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="other_drug_3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="other_drug_3_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="other_drug_3_dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="passing_urine",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="physical_exam_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="referral_source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="respiratory_rate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="rutf_ration_per_day",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="rutf_sachets_given",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="skin_changes",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="stool_frequency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="temperature_celsius",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="travel_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="vitamin_a_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="vitamin_a_dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="vomiting",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="opcregistration",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated: CODE/NNN/SAM/OPC",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="opcregistration",
            name="z_score_hfa",
            field=models.CharField(
                blank=True,
                help_text="Z-score category or numeric value",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="opcregistration",
            name="z_score_wfa",
            field=models.CharField(
                blank=True,
                help_text="Z-score category or numeric value",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="opcregistration",
            name="z_score_wfh",
            field=models.CharField(
                blank=True,
                help_text="Z-score category or numeric value",
                max_length=50,
                null=True,
            ),
        ),
    ]
