# Generated migration for Task/Workflow Management System
# Enables automated task creation and tracking for SAM OPC cases

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0001_initial'),
        ('cases', '0007_advanced_automation_fields'),
    ]

    operations = [
        # ═══════════════════════════════════════════════════════════════
        # TASK MANAGEMENT SYSTEM
        # ═══════════════════════════════════════════════════════════════
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(
                    max_length=50,
                    choices=[
                        ('ipc_referral', 'IPC Referral'),
                        ('home_visit', 'Home Visit'),
                        ('appetite_test', 'Appetite Test Required'),
                        ('amoxicillin_treatment', 'Amoxicillin Treatment'),
                        ('malaria_test', 'Malaria Test'),
                        ('deworming', 'Deworming (Week 2)'),
                        ('measles_vaccine', 'Measles Vaccination (Week 4)'),
                        ('medical_investigation', 'Medical Investigation'),
                        ('discharge_counseling', 'Discharge Counseling'),
                        ('community_linkage', 'Community Follow-up Linkage'),
                        ('nutrition_education', 'Nutrition Education'),
                        ('immunization_check', 'Immunization Status Check'),
                        ('rutf_ration', 'RUTF Ration Preparation'),
                        ('weight_monitoring', 'Weight Monitoring Alert'),
                        ('oedema_check', 'Oedema Reduction Check'),
                    ],
                    help_text='Type of task to be completed'
                )),
                ('priority', models.CharField(
                    max_length=20,
                    choices=[
                        ('critical', 'Critical'),
                        ('high', 'High'),
                        ('medium', 'Medium'),
                        ('low', 'Low'),
                    ],
                    default='medium',
                    help_text='Task priority level'
                )),
                ('status', models.CharField(
                    max_length=20,
                    choices=[
                        ('pending', 'Pending'),
                        ('in_progress', 'In Progress'),
                        ('completed', 'Completed'),
                        ('cancelled', 'Cancelled'),
                        ('overdue', 'Overdue'),
                    ],
                    default='pending',
                    help_text='Current task status'
                )),
                ('title', models.CharField(
                    max_length=255,
                    help_text='Short task title'
                )),
                ('description', models.TextField(
                    help_text='Detailed task description'
                )),
                ('trigger_reason', models.TextField(
                    null=True,
                    blank=True,
                    help_text='Reason why this task was auto-generated'
                )),
                ('due_date', models.DateField(
                    null=True,
                    blank=True,
                    help_text='Date by which task should be completed'
                )),
                ('completed_date', models.DateTimeField(
                    null=True,
                    blank=True,
                    help_text='Date and time task was completed'
                )),
                ('completion_notes', models.TextField(
                    null=True,
                    blank=True,
                    help_text='Notes about task completion'
                )),
                ('auto_generated', models.BooleanField(
                    default=False,
                    help_text='True if task was auto-generated by automation rules'
                )),
                ('registration', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='tasks',
                    to='cases.opcregistration',
                    help_text='Associated OPC registration'
                )),
                ('visit', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='tasks',
                    to='cases.opcvisit',
                    null=True,
                    blank=True,
                    help_text='Associated visit (if task is visit-specific)'
                )),
                ('assigned_to', models.ForeignKey(
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='assigned_tasks',
                    to=settings.AUTH_USER_MODEL,
                    null=True,
                    blank=True,
                    help_text='Staff member assigned to this task'
                )),
                ('created_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='tasks_created',
                    to=settings.AUTH_USER_MODEL,
                    help_text='User who created this task'
                )),
                ('completed_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='tasks_completed',
                    to=settings.AUTH_USER_MODEL,
                    null=True,
                    blank=True,
                    help_text='User who completed this task'
                )),
                ('facility', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='case_tasks',
                    to='facilities.facility',
                    help_text='Facility where task should be completed'
                )),
            ],
            options={
                'db_table': 'case_tasks',
                'verbose_name': 'Case Task',
                'verbose_name_plural': 'Case Tasks',
                'ordering': ['-priority', 'due_date', '-created_at'],
                'indexes': [
                    models.Index(fields=['status', 'priority'], name='task_status_priority_idx'),
                    models.Index(fields=['registration', 'status'], name='task_reg_status_idx'),
                    models.Index(fields=['due_date'], name='task_due_date_idx'),
                ],
            },
        ),
        
        # ═══════════════════════════════════════════════════════════════
        # WORKFLOW TEMPLATES (Optional - for future use)
        # ═══════════════════════════════════════════════════════════════
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(
                    max_length=255,
                    help_text='Workflow template name'
                )),
                ('description', models.TextField(
                    help_text='Workflow description'
                )),
                ('trigger_condition', models.CharField(
                    max_length=100,
                    choices=[
                        ('admission', 'On Admission'),
                        ('visit', 'On Visit'),
                        ('week_2', 'At Week 2'),
                        ('week_4', 'At Week 4'),
                        ('ipc_referral', 'IPC Referral Triggered'),
                        ('weight_loss', 'Weight Loss Detected'),
                        ('non_response', 'Non-Response Detected'),
                    ],
                    help_text='Condition that triggers this workflow'
                )),
                ('task_definitions', models.JSONField(
                    help_text='JSON array of task definitions to create'
                )),
                ('is_active', models.BooleanField(
                    default=True,
                    help_text='Whether this workflow template is active'
                )),
            ],
            options={
                'db_table': 'workflow_templates',
                'verbose_name': 'Workflow Template',
                'verbose_name_plural': 'Workflow Templates',
            },
        ),
    ]
