# Generated by Django 5.0.1 on 2026-06-27 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_task_workflow_system'),
        ('facilities', '0002_add_population_sam_prevalence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcregistration',
            name='admission_basis',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='auto_admission_type',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='auto_discharge_category',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='auto_discharge_eligible',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='below_admission_weight_week_3',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='clinically_well_consecutive_count',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='consecutive_recovery_visits',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='consecutive_static_weight_count',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='consecutive_weight_loss_count',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='immunization_updated',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='is_new_case',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='last_visit_date',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='last_weight_kg',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='linked_to_followup',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='medical_investigation_done',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='missed_consecutive_visits',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='muac_12_5_consecutive_count',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='no_oedema_consecutive_count',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='nutrition_education_completed',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='registration_source_type',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='reporting_category',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='total_visits_count',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='weeks_in_treatment',
        ),
        migrations.RemoveField(
            model_name='opcregistration',
            name='wflh_recovery_consecutive_count',
        ),
        migrations.RemoveField(
            model_name='opcvisit',
            name='auto_action_reasons',
        ),
        migrations.RemoveField(
            model_name='opcvisit',
            name='auto_suggested_action',
        ),
        migrations.RemoveField(
            model_name='opcvisit',
            name='home_visit_triggered',
        ),
        migrations.RemoveField(
            model_name='opcvisit',
            name='ipc_referral_triggered',
        ),
        migrations.RemoveField(
            model_name='opcvisit',
            name='weight_change_grams',
        ),
        migrations.RemoveField(
            model_name='opcvisit',
            name='weight_gain_per_kg_per_day',
        ),
        migrations.RemoveField(
            model_name='opcvisit',
            name='weight_trend',
        ),
        migrations.AlterField(
            model_name='casetask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='completion_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_tasks', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.opcregistration'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='task_type',
            field=models.CharField(choices=[('ipc_referral', 'IPC Referral'), ('home_visit', 'Home Visit'), ('appetite_test', 'Appetite Test Required'), ('amoxicillin_treatment', 'Amoxicillin Treatment'), ('malaria_test', 'Malaria Test'), ('deworming', 'Deworming (Week 2)'), ('measles_vaccine', 'Measles Vaccination (Week 4)'), ('medical_investigation', 'Medical Investigation'), ('discharge_counseling', 'Discharge Counseling'), ('community_linkage', 'Community Follow-up Linkage'), ('nutrition_education', 'Nutrition Education'), ('immunization_check', 'Immunization Status Check'), ('rutf_ration', 'RUTF Ration Preparation'), ('weight_monitoring', 'Weight Monitoring Alert'), ('oedema_check', 'Oedema Reduction Check')], max_length=50),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='trigger_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.opcvisit'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='task_definitions',
            field=models.JSONField(help_text='JSON array of task definitions'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='trigger_condition',
            field=models.CharField(choices=[('admission', 'On Admission'), ('visit', 'On Visit'), ('week_2', 'At Week 2'), ('week_4', 'At Week 4'), ('ipc_referral', 'IPC Referral Triggered'), ('weight_loss', 'Weight Loss Detected'), ('non_response', 'Non-Response Detected')], max_length=100),
        ),
    ]
