# Generated by Django 4.2.27 on 2026-07-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_mam_opc_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opcvisit",
            name="z_score_hfa",
            field=models.CharField(
                blank=True,
                help_text="Z-score category or numeric value",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="opcvisit",
            name="z_score_wfa",
            field=models.CharField(
                blank=True,
                help_text="Z-score category or numeric value",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="opcvisit",
            name="z_score_wfh",
            field=models.CharField(
                blank=True,
                help_text="Z-score category or numeric value",
                max_length=50,
                null=True,
            ),
        ),
    ]
