# Generated by Django 4.2.27 on 2026-07-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_remove_opcregistration_age_under_24_months_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcregistration",
            name="counselling",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="failed_counselling_only",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="food_product_quantity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="food_product_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="hiv_tb_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="household_vulnerability",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="immunization_action",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="mebendazole_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="mother_deceased",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="other_medicines",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="poor_maternal_health",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="previous_sam_episode",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcvisit",
            name="chest_indrawing",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcvisit",
            name="convulsions",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcvisit",
            name="intractable_vomiting",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcvisit",
            name="lethargic_or_not_alert",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcvisit",
            name="severe_dehydration",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcvisit",
            name="unconscious",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcvisit",
            name="very_pale_or_severe_palmar_pallor",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
