# Generated by Django 5.1.5 on 2026-07-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0014_opcregistration_counselling_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opcvisit",
            name="weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
