# Generated by Django 5.1.5 on 2026-07-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0015_alter_opcvisit_weight_kg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipccase",
            name="status",
            field=models.CharField(
                choices=[
                    ("Admitted", "Admitted"),
                    ("Discharged", "Discharged"),
                    ("Death", "Death"),
                    ("Defaulted", "Defaulted"),
                    ("Transfer", "Transfer"),
                ],
                default="Admitted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mamcase",
            name="status",
            field=models.CharField(
                choices=[
                    ("Admitted", "Admitted"),
                    ("Discharged", "Discharged"),
                    ("Death", "Death"),
                    ("Defaulted", "Defaulted"),
                    ("Transfer", "Transfer"),
                ],
                default="Admitted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="opcregistration",
            name="height_cm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="opcregistration",
            name="weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="samcase",
            name="status",
            field=models.CharField(
                choices=[
                    ("Admitted", "Admitted"),
                    ("Discharged", "Discharged"),
                    ("Death", "Death"),
                    ("Defaulted", "Defaulted"),
                    ("Transfer", "Transfer"),
                ],
                default="Admitted",
                max_length=50,
            ),
        ),
    ]
