# Generated by Django 5.1.5 on 2026-08-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0016_alter_ipccase_status_alter_mamcase_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="facility",
        ),
        migrations.RemoveField(
            model_name="samcase",
            name="facility",
        ),
        migrations.DeleteModel(
            name="MamCase",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
        migrations.DeleteModel(
            name="SamCase",
        ),
    ]
