# Generated by Django 5.1.5 on 2026-08-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_remove_patient_facility_remove_samcase_facility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcregistration",
            name="total_household_members",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
