# Generated by Django 5.1.5 on 2026-08-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0018_opcregistration_total_household_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opcvisit",
            name="appetite",
            field=models.CharField(
                blank=True,
                choices=[("Pass", "Pass"), ("Fail", "Fail")],
                max_length=10,
                null=True,
            ),
        ),
    ]
