# Generated by Django 5.1.5 on 2026-08-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_alter_opcvisit_appetite"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcregistration",
            name="convulsions",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="intractable_vomiting",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="lethargic_or_not_alert",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="severe_dehydration",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="unconscious",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="very_pale_or_severe_palmar_pallor",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
