# Generated by Django 5.1.5 on 2026-08-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0020_add_ipc_clinical_signs_to_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcregistration",
            name="age_weeks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="effective_suckling",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="relactation_needed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="visible_severe_wasting",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
