# Generated by Django 5.1.5 on 2026-08-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0021_add_infant_assessment_fields_to_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcregistration",
            name="admission_time",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="bilateral_pitting_oedema",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="complications_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="oedema_grade",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="referring_facility",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="time_to_travel_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
