# Generated by Django 5.1.5 on 2026-08-08 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0022_add_admission_clinical_detail_fields"),
        ("facilities", "0003_add_opc_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilitySequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("malnutrition_type", models.CharField(max_length=10)),
                ("last_sequence", models.PositiveIntegerField(default=0)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "db_table": "facility_sequences",
                "unique_together": {("facility", "malnutrition_type")},
            },
        ),
    ]
