# Generated by Django 5.1.5 on 2026-08-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0024_backfill_facility_sequences"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcregistration",
            name="clinically_well_consecutive_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="consecutive_recovery_visits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="consecutive_static_weight_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="consecutive_weight_loss_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="immunization_updated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="linked_to_followup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="mam_missed_consecutive_visits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="mam_muac_12_5_consecutive_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="mam_treatment_period_weeks",
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="mam_weeks_in_treatment",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="medical_investigation_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="missed_consecutive_visits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="muac_12_5_consecutive_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="no_oedema_consecutive_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="nutrition_education_completed",
            field=models.BooleanField(default=False),
        ),
    ]
