# Generated by Django 5.1.5 on 2026-09-02 07:23

from django.db import migrations, models
import hashlib
import json
import unicodedata


def _normalise(value):
    return ' '.join(unicodedata.normalize('NFKC', str(value or '')).casefold().split())


def _digest(parts):
    return hashlib.sha256('|'.join(str(part or '') for part in parts).encode('utf-8')).hexdigest()


def populate_keys_and_remove_safe_duplicates(apps, schema_editor):
    OpcRegistration = apps.get_model('cases', 'OpcRegistration')
    IpcCase = apps.get_model('cases', 'IpcCase')
    StockMovement = apps.get_model('inventory', 'StockMovement')
    RiskPrediction = apps.get_model('ai', 'RiskPrediction')
    AuditLog = apps.get_model('users', 'AuditLog')

    groups = {}
    for case in OpcRegistration.objects.all().order_by('id'):
        key = _digest([
            case.facility_id, _normalise(case.child_name), case.date_of_birth,
            case.admission_date, _normalise(case.caregiver_name),
        ])
        groups.setdefault(key, []).append(case)

    for key, cases in groups.items():
        canonical = max(cases, key=lambda case: (case.visits.count(), case.tasks.count(), -case.id))
        for duplicate in cases:
            if duplicate.pk == canonical.pk:
                continue
            references = [f'REG-{duplicate.registration_number}']
            if duplicate.visits.exists() or duplicate.tasks.exists() or RiskPrediction.objects.filter(registration_id=duplicate.id).exists():
                raise RuntimeError(f'Duplicate case {duplicate.id} has related clinical data and requires manual merge.')
            if StockMovement.objects.filter(reference_number__in=references).exists():
                raise RuntimeError(f'Duplicate case {duplicate.id} has stock movements and requires manual reversal.')
            AuditLog.objects.create(
                user_id=None,
                action='delete',
                resource_type='OpcRegistrationDuplicate',
                resource_id=duplicate.id,
                details=json.dumps({
                    'reason': 'Exact duplicate removed during deduplication migration',
                    'kept_registration_id': canonical.id,
                    'removed_registration_number': duplicate.registration_number,
                }),
            )
            duplicate.delete()
        canonical.deduplication_key = key
        canonical.save(update_fields=['deduplication_key'])

    ipc_groups = {}
    for case in IpcCase.objects.all().order_by('id'):
        key = _digest([
            case.facility_id, _normalise(case.patient_name),
            case.admission_date, _normalise(case.gender),
        ])
        ipc_groups.setdefault(key, []).append(case)

    for key, cases in ipc_groups.items():
        canonical = cases[0]
        for duplicate in cases[1:]:
            AuditLog.objects.create(
                user_id=None,
                action='delete',
                resource_type='IpcCaseDuplicate',
                resource_id=duplicate.id,
                details=json.dumps({
                    'reason': 'Exact duplicate removed during deduplication migration',
                    'kept_case_id': canonical.id,
                }),
            )
            duplicate.delete()
        canonical.deduplication_key = key
        canonical.save(update_fields=['deduplication_key'])


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0025_automation_tracking_fields"),
        ("ai", "0001_initial"),
        ("inventory", "0006_remove_unit_cost_fields"),
        ("users", "0005_add_push_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipccase",
            name="client_uid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="ipccase",
            name="deduplication_key",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="client_uid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="opcregistration",
            name="deduplication_key",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="opcvisit",
            name="client_uid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(populate_keys_and_remove_safe_duplicates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="ipccase",
            name="deduplication_key",
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="opcregistration",
            name="deduplication_key",
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
