# Generated by Django 5.1.5 on 2026-09-04 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0027_rebuild_registration_deduplication_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationMerge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_id", models.PositiveBigIntegerField(unique=True)),
                (
                    "original_client_uid",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                ("original_key", models.CharField(max_length=64, unique=True)),
                ("snapshot", models.JSONField()),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        null=True,
                        related_name="merged_registrations",
                        to="cases.opcregistration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
