# Generated by Django 4.2.27 on 2026-07-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_avatar_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_discharge",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_stock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_visits",
            field=models.BooleanField(default=True),
        ),
    ]
