# Generated by Django 5.0.1 on 2026-03-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Therapeutic Foods', 'Therapeutic Foods'), ('Supplements', 'Supplements'), ('Medicines', 'Medicines'), ('Medical Supplies', 'Medical Supplies'), ('RUTF', 'Ready-to-Use Therapeutic Food'), ('RUSF', 'Ready-to-Use Supplementary Food'), ('CSB', 'Corn-Soya Blend'), ('F75', 'F-75 Therapeutic Milk'), ('F100', 'F-100 Therapeutic Milk'), ('ReSoMal', 'ReSoMal'), ('Oil', 'Fortified Vegetable Oil'), ('Sugar', 'Sugar'), ('Medicine', 'Medicine'), ('Supply', 'Medical Supply'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(choices=[('Sachets', 'Sachets'), ('Cartons', 'Cartons'), ('Packets', 'Packets'), ('Tins', 'Tins'), ('Bottles', 'Bottles'), ('Kg', 'Kilograms'), ('Litres', 'Litres'), ('Pieces', 'Pieces'), ('Boxes', 'Boxes'), ('Units', 'Units')], max_length=50)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_stock_level', models.IntegerField(default=0, help_text='Minimum stock level before alert')),
                ('reorder_level', models.IntegerField(default=0, help_text='Level at which to reorder')),
                ('max_stock_level', models.IntegerField(default=0, help_text='Maximum stock capacity')),
                ('has_expiry', models.BooleanField(default=False, help_text='Does this item have expiry dates?')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_conditions', models.CharField(blank=True, choices=[('Room Temp', 'Room Temperature (15-25°C)'), ('Cool Dry', 'Cool and Dry Place'), ('Refrigerated', 'Refrigerated (2-8°C)'), ('Frozen', 'Frozen (-20°C)')], max_length=50, null=True)),
                ('initial_stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('location_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_disposed', models.BooleanField(default=False)),
                ('disposed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Item Batch',
                'verbose_name_plural': 'Item Batches',
                'db_table': 'item_batches',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_type', models.CharField(choices=[('national', 'National'), ('regional', 'Regional'), ('district', 'District'), ('facility', 'Facility')], max_length=50)),
                ('current_stock', models.IntegerField(default=0)),
                ('reserved_stock', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Level',
                'verbose_name_plural': 'Stock Levels',
                'db_table': 'stock_levels',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment'), ('CONSUMPTION', 'Consumption')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_type', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('movement_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stock Request',
                'verbose_name_plural': 'Stock Requests',
                'db_table': 'stock_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_requested', models.IntegerField()),
                ('quantity_approved', models.IntegerField(blank=True, null=True)),
                ('quantity_fulfilled', models.IntegerField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stock Request Item',
                'verbose_name_plural': 'Stock Request Items',
                'db_table': 'stock_request_items',
            },
        ),
        migrations.CreateModel(
            name='FacilityConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_used', models.IntegerField()),
                ('consumption_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='facilities.facility')),
            ],
            options={
                'verbose_name': 'Facility Consumption',
                'verbose_name_plural': 'Facility Consumptions',
                'db_table': 'facility_consumptions',
                'ordering': ['-consumption_date'],
            },
        ),
    ]
