# Generated by Django 5.0.1 on 2026-03-22 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0004_add_admission_fields'),
        ('facilities', '0001_initial'),
        ('inventory', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityconsumption',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilityconsumption',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='cases.opcvisit'),
        ),
        migrations.AddField(
            model_name='facilityconsumption',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='itembatch',
            name='disposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itembatch',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.district'),
        ),
        migrations.AddField(
            model_name='itembatch',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='itembatch',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='itembatch',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.region'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.district'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.region'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_movements', to='locations.district'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_movements', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_movements', to='locations.region'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_movements', to='locations.district'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_movements', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_movements', to='locations.region'),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests_fulfilled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='requesting_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='locations.district'),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='requesting_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='requesting_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='locations.region'),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='supplier_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplied_requests', to='locations.district'),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='supplier_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplied_requests', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='supplier_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplied_requests', to='locations.region'),
        ),
        migrations.AddField(
            model_name='stockrequestitem',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stockrequestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together={('inventory_item', 'location_type', 'region', 'district', 'facility')},
        ),
    ]
