# Generated by Django 5.1.5 on 2026-07-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="conversion_factor",
            field=models.DecimalField(
                decimal_places=4,
                default=1.0,
                help_text="Multiplier to convert case-entry quantities (e.g. kg) into stock units (e.g. sachets).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="stockrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("partially_fulfilled", "Partially Fulfilled"),
                    ("fulfilled", "Fulfilled"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
