# Generated by Django 5.1.5 on 2026-07-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventoryitem_conversion_factor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="batch_number",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="manufacture_date",
        ),
    ]
