# Generated by Django 5.1.5 on 2026-07-30 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_inventoryitem_batch_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements",
                to="inventory.itembatch",
            ),
        ),
    ]
