# Generated by Django 5.1.5 on 2026-08-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_stockmovement_batch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="unit_cost",
        ),
        migrations.RemoveField(
            model_name="stockrequestitem",
            name="unit_cost",
        ),
    ]
